import { presetSettings } from "@shared/schema";

export const quickPresets: presetSettings[] = [
  {
    name: "Blue Professional",
    category:"dark colors",
    presetID:"blue-professional",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],
    className: "p-2 text-xs bg-blue-500 text-white rounded hover:bg-blue-600",
    presetValues: {
      primary: "#3b82f6",
      secondary: "#64748b",
      accent: "#06b6d4",
      background: "#ffffff",
      sidebarBackground: "#1e293b",
      headerTextColor: "#1e293b",
      bodyTextColor: "#374151",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Blue Professional",
    category:"dark colors",
    presetID:"blue-professional",
    forTemplates: ["14"],
    className: "p-2 text-xs bg-blue-500 text-white rounded hover:bg-blue-600",
    presetValues: {
      primary: "#facc15",
      secondary: "#64748b",
      accent: "#06b6d4",
      background: "#ffffff",
      sidebarBackground: "#1e293b",
      headerTextColor: "#1e293b",
      bodyTextColor: "#374151",
      sidebarTextColor: "#4d4d4d",
    },
  },
  {
    name: "Green professional",
    category:"dark colors",
    presetID:"Green-professional",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-green-600 text-white rounded hover:bg-green-700",
    presetValues: {
      primary: "#059669",
      secondary: "#64748b",
      accent: "#10b981",
      background: "#ffffff",
      sidebarBackground: "#065f46",
      headerTextColor: "#065f46",
      bodyTextColor: "#374151",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Red Bold",
    category:"dark colors",
    presetID:"Red-professional",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-red-600 text-white rounded hover:bg-red-700",
    presetValues: {
      primary: "#dc2626",
      secondary: "#64748b",
      accent: "#ef4444",
      background: "#ffffff",
      sidebarBackground: "#7f1d1d",
      headerTextColor: "#7f1d1d",
      bodyTextColor: "#374151",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Purple professional",
    category:"dark colors",
    presetID:"Purple-professional",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-purple-600 text-white rounded hover:bg-purple-700",
    presetValues: {
      primary: "#7c3aed",
      secondary: "#64748b",
      accent: "#8b5cf6",
      background: "#ffffff",
      sidebarBackground: "#400f66",
      headerTextColor: "#581c87",
      bodyTextColor: "#374151",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Light Amber",
    category:"Light colors",
    presetID:"Light-amber",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-amber-400 text-amber-900 rounded hover:bg-amber-500",
    presetValues: {
      primary: "#f59e0b",
      secondary: "#64748b",
      accent: "#fbbf24",
      background: "#ffffff",
      sidebarBackground: "#fef3c7",
      headerTextColor: "#92400e",
      bodyTextColor: "#374151",
      sidebarTextColor: "#92400e",
    },
  },
  {
    name: "Light Pink",
    category:"Light colors",
    presetID:"Light-pink",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-pink-400 text-pink-900 rounded hover:bg-pink-500",
    presetValues: {
      primary: "#ec4899",
      secondary: "#64748b",
      accent: "#f472b6",
      background: "#ffffff",
      sidebarBackground: "#fce7f3",
      headerTextColor: "#be185d",
      bodyTextColor: "#374151",
      sidebarTextColor: "#be185d",
    },
  },
  {
    name: "Light Cyan",
    category:"Light colors",
    presetID:"Light-cyan",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-cyan-400 text-cyan-900 rounded hover:bg-cyan-500",
    presetValues: {
      primary: "#06b6d4",
      secondary: "#64748b",
      accent: "#22d3ee",
      background: "#ffffff",
      sidebarBackground: "#e5f4ff",
      headerTextColor: "#0f766e",
      bodyTextColor: "#000000",
      sidebarTextColor: "#3d3d3d",
    },
  },
  {
    name: "Light Violet",
    category:"Light colors",
    presetID:"Light-Violet",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-violet-400 text-violet-900 rounded hover:bg-violet-500",
    presetValues: {
      primary: "#a807d5",
      secondary: "#64748b",
      accent: "#a78bfa",
      background: "#ffffff",
      sidebarBackground: "#fdf0ff",
      headerTextColor: "#990f8e",
      bodyTextColor: "#374151",
      sidebarTextColor: "#5c238b",
    },
  },

  {
    name: "Dark Slate",
    category:"dark theme",
    presetID:"Dark-Slate",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-slate-800 text-white rounded hover:bg-slate-900",
    presetValues: {
      primary: "#3b82f6",
      secondary: "#64748b",
      accent: "#06b6d4",
      background: "#0f172a",
      sidebarBackground: "#1e293b",
      headerTextColor: "#f1f5f9",
      bodyTextColor: "#e2e8f0",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Dark Emerald",
    category:"dark theme",
    presetID:"Dark-emerald",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-emerald-800 text-white rounded hover:bg-emerald-900",
    presetValues: {
      primary: "#10b981",
      secondary: "#64748b",
      accent: "#34d399",
      background: "#064e3b",
      sidebarBackground: "#065f46",
      headerTextColor: "#d1fae5",
      bodyTextColor: "#a7f3d0",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Dark Amber",
    category:"dark theme",
    presetID:"Dark-Amber",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-amber-800 text-white rounded hover:bg-amber-900",
    presetValues: {
      primary: "#f59e0b",
      secondary: "#64748b",
      accent: "#fbbf24",
      background: "#451a03",
      sidebarBackground: "#78350f",
      headerTextColor: "#fef3c7",
      bodyTextColor: "#fed7aa",
      sidebarTextColor: "#ffffff",
    },
  },
  {
    name: "Dark Violet",
    category:"dark theme",
    presetID:"Dark-Violet",
    forTemplates: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],

    className: "p-2 text-xs bg-violet-800 text-white rounded hover:bg-violet-900",
    presetValues: {
      primary: "#8b5cf6",
      secondary: "#64748b",
      accent: "#a78bfa",
      background: "#2e1065",
      sidebarBackground: "#4c1d95",
      headerTextColor: "#ede9fe",
      bodyTextColor: "#c4b5fd",
      sidebarTextColor: "#ffffff",
    },
  },
];